### DISCUSSION TITLE
Docker container keeps changing folder permissions

### DISCUSSION THREAD

**Discussion by NooNameR** [arabcoders/ytptube#280] [General] [answered]
```.env
PUID=99
PGID=100
UMASK=022
```

```yaml
ytptube:
    extends:
      file: ../docker-compose.template.yml
      service: common
    image: ghcr.io/arabcoders/ytptube:latest
    user: $PUID:$PGID
    container_name: ytptube
    volumes:
      - $APP_DATA/ytptube:/config:rw
      - $DATA/media/youtube:/data/media/youtube
    environment:
      YTP_DOWNLOAD_PATH: /data/media/youtube
      YTP_KEEP_ARCHIVE: false
```

confirmed with inspect:
```
"User": "99:100",
```

After any download it changes permission to be `1000:1000`
