### ISSUE TITLE
[BUG] Queued Videos Remain in Loading State (Temporary File Issue?)

### ISSUE THREAD

**Issue by engels74** [arabcoders/ytptube#173]
**[BUG] Queued Videos Remain in Loading State (Temporary File Issue?)**

### **Description**
After setting up `ytptube` with the provided configuration, videos are downloaded successfully, but the queued videos remain in a loading state indefinitely. The issue persists even though the downloaded files are accessible and complete.

---

#### `compose.yaml`
```yaml
services:
  ytptube:
    container_name: ytptube
    hostname: ytptube.internal
    image: ghcr.io/arabcoders/ytptube
    user: 1000:1000
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=https://discord.com/api/webhooks/xxxxxxxx/xxxxxxxxxx"
      - "org.hotio.pullio.author.avatar=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/youtube.webp"
    volumes:
      - /opt/docker-all/miscSoftware/ytptube/config:/config:rw  # Configuration files
      - /opt/docker-all/miscSoftware/ytptube/downloads:/downloads:rw  # Downloaded files
    tmpfs:
      - /tmp
    environment:
      - TZ=Europe/Copenhagen
      - YTP_CONFIG_PATH=/config
      - YTP_DOWNLOAD_PATH=/downloads
      - YTP_TEMP_PATH=/tmp
      - YTP_TEMP_KEEP=false  # Delete temporary files after download
      - YTP_KEEP_ARCHIVE=false  # Disable download history to save space
      - YTP_REMOVE_FILES=true  # Delete files when removed from the UI
      - YTP_MAX_WORKERS=2  # Limit concurrent downloads
      - YTP_LOG_LEVEL=info  # Reduce logging verbosity
      - YTP_ACCESS_LOG=false  # Disable access logs
      - YTP_DEBUG=false  # Disable debug mode
      - YTP_UI_UPDATE_TITLE=true  # Keep UI updated
      - YTP_ALLOW_MANIFESTLESS=true  # Allow downloading live streams
      - YTP_BASIC_MODE=true
    networks:
      - caddy_backbone
    restart: always

networks:
  caddy_backbone:
    external: true
```

#### File Permissions
The download folder is owned by the `xvps` user (UID 1000), which has the correct group permissions:
```bash
xvps@l7ext2:~$ id
uid=1000(xvps) gid=1000(xvps) groups=1000(xvps),27(sudo),100(users),988(docker)

xvps@l7ext2:~$ ls -alh /opt/docker-all/miscSoftware/
total 16K
drwxr-xr-x 4 xvps xvps 4.0K Jan 15 22:27 .
drwxr-xr-x 3 xvps xvps 4.0K Jan 15 22:10 ..
drwxrwxr-x 4 xvps xvps 4.0K Jan 16 12:29 caddy
drwxr-xr-x 4 xvps xvps 4.0K Jan 17 21:30 ytptube

xvps@l7ext2:~$ ls -alh /opt/docker-all/miscSoftware/ytptube/
total 16K
drwxr-xr-x 4 xvps xvps 4.0K Jan 17 21:30 .
drwxr-xr-x 4 xvps xvps 4.0K Jan 15 22:27 ..
drwxr-xr-x 2 xvps xvps 4.0K Jan 17 21:21 config
drwxr-xr-x 2 xvps xvps 4.0K Jan 17 21:21 downloads
```

#### `ytdlp.json`
```json
{
  "format": "bv*[height<=1080]+ba/b[height<=1080]",
  "merge_output_format": "mkv",
  "outtmpl": "%(title)s.%(ext)s",
  "restrictfilenames": true,
  "nooverwrites": true,
  "noplaylist": true,
  "verbose": true
}
```

---

### **Steps to Reproduce**
1. Set up `ytptube` using the provided `compose.yaml` and `ytdlp.json` configurations.
2. Queue a video for download (e.g., `https://www.youtube.com/watch?v=wF4R597ANIE`).
3. Observe that the video remains in a loading state in the queue, even though the file is fully downloaded and accessible.

---

### **Expected Behavior**
The queued video should complete its loading state and disappear from the queue once the download is finished.

---

### **Actual Behavior**
The queued video remains in a loading state indefinitely, despite the file being successfully downloaded.

---

### **Logs**
Logs can be found here:  
[Log File](https://logs.notifiarr.com/?4983ca641e4a947b#E5QwokCZoyFUcv9SwhootiNDqpH9ZihFkj6HCNUfZ2X9)

---

### **Screenshots**
https://i.postimg.cc/RVyM3gYp/SCR-20250117-lkox-2.png
