### ISSUE TITLE
[BUG]%(playlist_autonumber)s, %(playlist_index)s not working properly

### ISSUE THREAD

**Issue by anonymous-99529** [arabcoders/ytptube#227]
`%(playlist_autonumber)s`, `%(playlist_index)s` not working.

version: latest(master-20250325-fd93472)

my ytdlp.json:

```json
{
  "live_from_start": true,
  "continue_dl": true,
  "windowsfilenames": true,
  "playlistreverse": true,
  "writethumbnail": true,
  "writesubtitles": true,
  "postprocessors": [{"key": "EmbedThumbnail", "already_have_thumbnail": false}, {"key": "FFmpegMetadata"}, {"key": "FFmpegEmbedSubtitle"}],
  "merge_output_format": "mp4"
}
```

<br><br>

my docker-compose.yml:

```yml
version: '3.8'

services:
  ytptube:
    image: ghcr.io/arabcoders/ytptube
    container_name: ytptube
    hostname: ytptube
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - {my docker directory}/ytptube/config:/config
      - {my docker directory}/ytptube:/downloads
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /tmp
    user: '{my UID}:{my GID}'
    environment:
      - YTP_OUTPUT_TEMPLATE=%(webpage_url_domain)s/%(channel)s/%(playlist_title)s/%(playlist_autonumber)s%(playlist_autonumber&. )s%(title)s.%(ext)s
      - YTP_KEEP_ARCHIVE=false
    stdin_open: true
    tty: true
    restart: unless-stopped
```

<br><br>

so, the `YTP_OUTPUT_TEMPLATE` I set is this:

```yml
    environment:
      - YTP_OUTPUT_TEMPLATE=%(webpage_url_domain)s/%(channel)s/%(playlist_title)s/%(playlist_autonumber)s%(playlist_autonumber&. )s%(title)s.%(ext)s
```

expected output filename example:

`youtube.com/a/b/01. video.mp4`

actual output filename example:

`youtube.com/a/b/NANAvideo.mp4`

<br><br>

by replacing `%(playlist_autonumber)s` with `%(playlist_index)s`:

expected output filename example:

`youtube.com/a/b/01. video.mp4`

actual output filename example:

`youtube.com/a/b/01NAvideo.mp4`

<br><br>

Things I've tried:

- I tried downloading the video with the exact same output template with yt-dlp installed on my Desktop, and I got the result I wanted.
- I removed all files in the `/config` folder except for `ytdlp.json`, and redeployed (several times).
